### ISSUE TITLE
Simplecov - uninitialiazed constant Simpleco

### ISSUE THREAD

**Issue by icebox827** [simplecov-ruby/simplecov#1009]
Running a rails 4.2.7 app with Ruby 2.3.8
1. `bundle install` ran without any error
2. `bundle update` ran without any error
3. `rake db:create` Produced the error below

```
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/app_rails_loader.rb:39: warning: Insecure world writable dir /mnt/c/Python310/Scripts/ in PATH, mode 040777
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'simplecov-html'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant SimpleCov
Backtrace for gem load error is:
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/simplecov-html-0.10.2/lib/simplecov-html.rb:8:in `<top (required)>'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/home/icebo/rails_online_ordering/config/application.rb:8:in `<top (required)>'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `require'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `block in server'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `tap'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `server'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
        from /home/icebo/rails_online_ordering/config/application.rb:8:in `<top (required)>'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/icebo/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

Please help me figure out what is broken in the app.

**Comment by PragTob** [comment]
Hi there, seems like SimpleCov isn't loaded/required/correctly defined as a dependency. Is `require 'simplecov'` in the right place?

That aside, Ruby 2.3 is no longer officially supported so I'm closing this.
