### ISSUE TITLE
missing dependency on 'etc'

### ISSUE THREAD

**Issue by and0x000** [simplecov-ruby/simplecov#918]
related to https://github.com/simplecov-ruby/simplecov/issues/917

simplecov requires the gem `etc` but does not list it as a dependency.

https://github.com/simplecov-ruby/simplecov/blob/main/lib/simplecov/load_global_config.rb#L3

This can become a problem, as `etc` is not necessarily installed with ruby, e.g. on alpine.

```
docker run --rm -ti alpine:edge /bin/sh                  
/ # apk --update add ruby build-base ruby-dev
[...]
/ # ruby -v 
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
/ # gem list | grep etc
/ # gem install simplecov pry json
Fetching simplecov-html-0.12.2.gem
Fetching simplecov-0.19.0.gem
Fetching docile-1.3.2.gem
Successfully installed docile-1.3.2
Successfully installed simplecov-html-0.12.2
Successfully installed simplecov-0.19.0
Fetching method_source-1.0.0.gem
Fetching pry-0.13.1.gem
Fetching coderay-1.1.3.gem
Successfully installed coderay-1.1.3
Successfully installed method_source-1.0.0
Successfully installed pry-0.13.1
Fetching json-2.3.1.gem
Building native extensions. This could take a while...
Successfully installed json-2.3.1
7 gems installed
/ # pry
[1] pry(main)> require 'simplecov'
LoadError: cannot load such file -- etc
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Caused by LoadError: cannot load such file -- simplecov
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**Comment by PragTob** [comment]
See #917 for rational
